
	## package managers

	### dnf
	alias "d"="dnf"
	alias "sd"="sudo dnf"
	
    ### nala
	alias "n"="nala"
	alias "sn"="sudo nala"

    ### pacman
    alias "sps"="sudo pacman -S"
    alias "pss"="pacman -Ss"
    alias "spu"="sudo pacman -Syu"


	## other aliases
	alias "nf"="nnn -d"
	alias "ll"="ls -la"
	alias "shutdown"="systemctl poweroff"
	alias "reboot"="systemctl reboot"
	alias ls="ls --color=auto"
	alias grep="grep --color=auto" 
