#! /bin/sh

pgrep -x sxhkd > /dev/null || 
sxhkd &

bspc monitor DP-0 -d  1 2 3 4 5 6 7 8 9 0

bspc config border_width         3
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom --config ~/.config/picom/picom.conf &
polybar &
nm-applet &
/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
$HOME/.screenlayout/Monitor.sh
nitrogen --restore &
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
xinput set-prop  'Microsoft Microsoft 5-Button Mouse with IntelliEye(TM)' 'libinput Accel Speed' -0.9
bspc desktop -f 1
