#! /bin/sh

## Start SXHKD for shortcuts
pgrep -x sxhkd > /dev/null || 
sxhkd &


## Enable 10 workspaces
bspc monitor -d  1 2 3 4 5 6 7 8 9 0

## Configure Border width
bspc config border_width         3

## Configure gap between windows
bspc config window_gap           5


bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## Border Colors
bspc config normal_border_color "#404040"
bspc config active_border_color "#8e60f7"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"


## Start up 
polybar &
nm-applet &
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
