#! /bin/sh

pgrep -x sxhkd > /dev/null || 
sxhkd &

bspc monitor DP-0 -d  1 2 3 4 5 6 7 8 9 0

bspc config border_width         3
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#8e60f7"
bspc config focused_border_color "#8e60f7"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom --config ~/.config/picom/picom.conf &
polybar &
$HOME/.config/bspwm/devicespecific/devicespecific
