
export EDITOR=nvim
export TERMINAL=alacritty
export WLR_NO_HARDWARE_CURSORS=1
export MOZ_ENABLE_WAYLAND=1

## NNN  Configuration
export NNN_PLUG='D:mkdir.sh;x:extract.sh;d:trash.sh;c:checksum.sh'

## sway config for Nvidia cards

# export WLR_RENDERER=vulkan
# export WLR_NO_HARDWARE_CURSORS=1
# export XWAYLAND_NO_GLAMOR=1
