# Lines configured by zsh-newuser-install
#

# If not interactive don't do anything
[[ "$-" != *i* ]] && return

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
export KEYTIMEOUT=1

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/user1/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Prompt
PROMPT=" %F{green}% %n%f:%F{blue}%~%f > "

# Aliases
	## package managers

	### dnf
	alias "d"="dnf"
	alias "sd"="sudo dnf"

	### nala
	alias "n"="nala"
	alias "sn"="sudo nala"

	### pacman
	alias "sps" "sudo pacman -S"
	alias "spu" "sudo pacman -Syu"
	alias "pss" "pacman -Ss"


	## other aliases
	alias "nf"="nnn -d"
	alias "ll"="ls -la"
	alias "shutdown"="systemctl poweroff"
	alias "reboot"="systemctl reboot"
	alias ls="ls --color=auto"
	alias grep="grep --color=auto" 
	alias "psu"="sudo pacman -Syu"

	## git alaiases
	alias "ga"="git add ."
	alias "gc"="git commit -m" 
	alias "gps"="git push origin main"
	alias "gpl"="git pull origin main"


zle-keymap-select()
{
    case $KEYMAP in
        vicmd) echo -ne '\e[3 q'
        ;;
        viins|main) echo -ne '\e[6 q'
        ;;
    esac
}

zle-line-init()
{
    echo -ne '\e[6 q'

}

zle -N zle-keymap-select
zle -N zle-line-init


autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line


