# Lines configured by zsh-newuser-install
#

# If not interactive don't do anything
[[ "$-" != *i* ]] && return

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
export KEYTIMEOUT=1

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/user1/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Prompt
PROMPT=" %F{green}% %n%f:%F{blue}%~%f > "

# Aliases
	## package managers

	### dnf
	alias "d"="dnf"
	alias "sd"="sudo dnf"

	### nala
	alias "n"="nala"
	alias "sn"="sudo nala"

	### pacman
	alias "sps" "sudo pacman -S"
	alias "spu" "sudo pacman -Syu"
	alias "pss" "pacman -Ss"


	## other aliases
	alias "nf"="nnn -d"
	alias "ll"="ls -la"
	alias "shutdown"="systemctl poweroff"
	alias "reboot"="systemctl reboot"
	alias ls="ls --color=auto"
	alias grep="grep --color=auto" 
	alias "psu"="sudo pacman -Syu"

	## git alaiases
	alias "ga"="git add ."
	alias "gc"="git commit -m" 
	alias "gps"="git push origin main"
	alias "gpl"="git pull origin main"


zle-keymap-select()
{
    case $KEYMAP in
        vicmd) echo -ne '\e[3 q'
        ;;
        viins|main) echo -ne '\e[6 q'
        ;;
    esac
}

zle-line-init()
{
    echo -ne '\e[6 q'

}

zle -N zle-keymap-select
zle -N zle-line-init


autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line


## Extract files
#
extract()
{
    case $1 in
        *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $1;;
        *.tar.gz|*.tgz) tar xzvf $1;;
        *.tar.xz|*.txz) tar xJvf $1;;
        *.zip) unzip $1;;
        *.rar) unrar x $1;;
        *.7z) 7z x $1;;
    esac
}

	gO()
	{
	    echo "What programm (has to be GUI)?";
	    read programm;
	    nohup $programm $1 & sleep 1; 
	    rm nohup.out;
	}
